modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"

[[mods]]
modId="minewatch"
version="1.0.0"
displayName="MineWatch"
authors="Gabrielsim"
description="HolyWorld mine cooldown HUD"

[[dependencies.minewatch]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="CLIENT"

[[dependencies.minewatch]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="CLIENT"
